server:
  address: 192.168.70.238
  port: 8000
eureka:
  instance:
    hostname: server
  client:
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

